### ISSUE TITLE
Building master branch on MacOS renders black canvas output

### ISSUE THREAD

**Issue by giraphics** [SergioRZMasson/BabylonNativeGLFWExample#1]
Hi Sergio,

Thanks for researching this topic, I am indeed looking for surfacing with GLFW.
I am building the master branch MacOS. The project builds successfully. However, I am unable to see anything. It seems that the GLFW appears with a black canvas.

Build steps:
```
git clone --recurse-submodules -j8 https://github.com/SergioRZMasson/BabylonNativeGLFW.git
cd Dependencies/BabylonNative
cd Apps
npm install
cd ../../
npm install
mkdir build
cd build
cmake .. -G "Xcode" 
```

Am I missing something?

**Comment by SergioRZMasson** [comment]
I'm currently using kind of a hack to make it work on MacOS. There is an issue where the rendering stops working on Window resize that I'm trying to figure out. Can you try pressing R when the canvas is black? That should re-create everything Babylon Related and it fixes the issue for window resize. 

Also, as a side note, you don't need to call npm install under BabylonNative/Apps folder, that's only required for building their Playground and we are not doing that.

**Comment by giraphics** [comment]
Thanks, @SergioRZMasson, for this quick help, it works like a charm. 

I have a follow-up question: I have a library written in Babylon JS, andI published it as an npm package. Can I reuse it as it is? Where can I find the rule book for BabylonNative and samples for reference?

**Comment by SergioRZMasson** [comment]
Just for the record. I managed to fix the issue with resizing on Mac, I just needed to add ```glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API)```. You can pull the latest version so you don't have to press R every time.

Regarding libraries in theory you should be able to add your library to the  package.json and to the path to the scripts you care about to the BABYLON_SCRIPTS list in CMakeLists.txt. This will allow the project to copy your script to the executable folder so it can be found by the ```Babylon::ScriptLoader```.

In main.cpp you can use Babylon::ScriptLoader to load your library script after babylon.js scripts are loaded and before game.js. 

The documentation we have on Babylon Native is in the main github repo: https://github.com/BabylonJS/BabylonNative, the main thing to pay attention would be the list of missing features. We are actively working on bringing all features from babylon.js to Babylon Native, but there a change that something you library is using might not be available yet.

**Comment by giraphics** [comment]
Thanks for quickly addressing this issue I will pull and check.

The `Babylon::scriptLoader` is something I was looking for, and it seems your guidance has enough hints for me to tackle. 
Thanks again for the valuable information you shared to get up and started.
