### ISSUE TITLE
Mouse events does not pass to application when ImGUI dialog is open

### ISSUE THREAD

**Issue by giraphics** [SergioRZMasson/BabylonNativeGLFWExample#2]
Unable to make a pull request because of the access rights to the current repo.

This bug can be fixed following way:-
```
void mouse_button_callback(GLFWwindow *window, int button, int action, int mods)
{
    if (s_showImgui)
	{
		ImGuiIO& io = ImGui::GetIO();
		io.AddMouseButtonEvent(button, action);
		if (io.WantCaptureMouse)
			return;
	}
        // . . . .more code goes here
}
```

**Comment by giraphics** [comment]
Added suggestion.

**Comment by SergioRZMasson** [comment]
@giraphics , I don't send mouse events to babylon.js when ImGUI is open so they don't change te Babylon Scene, it by design. To change that behavior one can just remove the if (s_showImgui) check from the mouse event callback.
